# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10.21.0

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
# services:
#  - mysql:latest
#  - redis:latest
#  - postgres:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

variables:
  OUTPUT_DIR: "_book/"
  NETLIFY_AUTH_TOKEN: "***REMOVED***"
  NETLIFY_SITE_ID: "***REMOVED***"

# define stages
stages:
  - build
  - preview
  - deploy

# define before script
before_script:
  - npm prune
  - npm install

# define jobs
build_job:
  stage: build
  script: 
    - npm run build
  artifacts:
    paths:
      - "_book/"
  only:
    - branches

preview_job:
  stage: preview
  script:
    - node_modules/.bin/netlify deploy --dir=_book --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID
  dependencies:
    - build_job
  only:
    - branches

deploy_job:
  stage: deploy
  script:
    - node_modules/.bin/netlify deploy --dir=_book --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID --prod
  dependencies:
    - build_job
  when: manual
  only: 
    - master@uilicious/documentation/gitbook
  
